/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    screens: {
      xs: "375px",
      sm: "480px",
      md: "37.75em", // 604px
      lg: "50em", // 800px
      xl: "72em", // 1152px
    },
    extend: {
      borderRadius: {
        primary: "var(--border-radius-primary)" /* Inputs, Buttons */,
        secondary: "var(--border-radius-secondary)" /* Cards */,
        reset: "var(--border-radius-reset)" /* Border reset */,
        round: "var(--border-radius-round)" /* Rounded icon buttons */,
      },
      borderWidth: {
        "w-primary": "var(--border-width-primary)" /* Inputs */,
        "w-secondary": "var(--border-width-secondary)" /* Buttons */,
        "w-reset": "var(--border-width-reset)" /* Border reset */,
      },
      // the brand's light and dark values (styles/brand.css), for the classes that pair them
      backgroundColor: {
        normal: "#F4F2F0",
        "dark-normal": "#1B1A18",
        highlight: "#EDE8FC",
        "dark-highlight": "#221B3A",
        "callout-note": "#F3EFFD",
        "callout-dark-note": "#1C1730",
        "callout-caution": "#FBF4E3",
        "callout-dark-caution": "#261F12",
        "callout-danger": "#FDEEEC",
        "callout-dark-danger": "#2B1614",
        "callout-tip": "#EEF5F0",
        "callout-dark-tip": "#14201A",
        "link-code": "#EDE8FC",
        "link-dark-code": "#221B3A",
        code: "#F4F2F0",
        "dark-code": "#1F1D1B",
      },
      borderColor: {
        primary: "#E5E1DC",
        "dark-primary": "#2C2A27",
      },
      colors: {
        blue: {
          100: "var(--blue-100)",
          200: "var(--blue-200)",
          300: "var(--blue-300)",
          400: "var(--blue-400)",
          500: "var(--blue-500)",
          600: "var(--blue-600)",
          700: "var(--blue-700)",
          800: "var(--blue-800)",
          900: "var(--blue-900)",
        },
        gray: {
          100: "var(--gray-100)",
          200: "var(--gray-200)",
          300: "var(--gray-300)",
          400: "var(--gray-400)",
          500: "var(--gray-500)",
          600: "var(--gray-600)",
          700: "var(--gray-700)",
          800: "var(--gray-800)",
          900: "var(--gray-900)",
        },
        green: {
          100: "var(--green-100)",
          200: "var(--green-200)",
          300: "var(--green-300)",
          400: "var(--green-400)",
          500: "var(--green-500)",
          600: "var(--green-600)",
          700: "var(--green-700)",
          800: "var(--green-800)",
          900: "var(--green-900)",
        },
        orange: {
          100: "var(--orange-100)",
          200: "var(--orange-200)",
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
          800: "var(--orange-800)",
          900: "var(--orange-900)",
        },
        purple: {
          100: "var(--purple-100)",
          200: "var(--purple-200)",
          300: "var(--purple-300)",
          400: "var(--purple-400)",
          500: "var(--purple-500)",
          600: "var(--purple-600)",
          700: "var(--purple-700)",
          800: "var(--purple-800)",
          900: "var(--purple-900)",
        },
        red: {
          100: "var(--red-100)",
          200: "var(--red-200)",
          300: "var(--red-300)",
          400: "var(--red-400)",
          500: "var(--red-500)",
          600: "var(--red-600)",
          700: "var(--red-700)",
          800: "var(--red-800)",
          900: "var(--red-900)",
        },
        yellow: {
          100: "var(--yellow-100)",
          200: "var(--yellow-200)",
          300: "var(--yellow-300)",
          400: "var(--yellow-400)",
          500: "var(--yellow-500)",
          600: "var(--yellow-600)",
          700: "var(--yellow-700)",
          800: "var(--yellow-800)",
          900: "var(--yellow-900)",
        },
        primary: "var(--color-text-primary)",
        secondary: "var(--color-text-secondary)",
        heading: "var(--color-text-heading)",
        error: "var(--color-text-error)",
        warning: "var(--color-text-warning)",
        success: "var(--color-text-success)",
        info: "var(--color-text-info)",
        contrast: "var(--color-text-contrast)",
        link: "var(--color-text-link)",
        "link-hover": "var(--color-text-link-hover)",
        "link-pressed": "var(--color-text-link-pressed)",
        disabled: "var(--color-text-disabled)",
        placeholder: "var(--color-text-placeholder)",
        value: "var(--color-text-value)",
        label: "var(--color-text-label)",
        text: "var(--theme-text)",
        accent: "var(--theme-text-accent)",
        light: "var(--theme-text-light)",
        lighter: "var(--theme-text-lighter)",
        bg: "var(--theme-bg)",
        "bg-hover": "var(--theme-bg-hover)",
        "bg-offset": "var(--theme-bg-offset)",
        "bg-accent": "var(--theme-bg-accent)",
        divider: "var(--sc-line)",
        accent: "var(--theme-accent)",
        "code-text": "var(--theme-code-text)",
        "code-bg": "var(--theme-code-bg)",
        "background-primary": "var(--color-background-primary)",
        "background-secondary": "var(--color-background-secondary)",
        "background-error": "var(--color-background-error)",
        "background-contrast": "var(--color-background-contrast)",
        "background-warning": "var(--color-background-warning)",
        "background-success": "var(--color-background-success)",
        "background-info": "var(--color-background-info)",
        "background-disabled": "var(--color-background-disabled)",
        "code-inline-bg": "var(--theme-code-inline-bg)",
        "border-primary": "var(--color-border-primary)",
        "border-secondary": "var(--color-border-secondary)",
        "border-contrast": "var(--color-border-contrast)",
        "border-interactive": "var(--color-border-interactive)",
        "border-disabled": "var(--color-border-disabled)",
        "border-separator": "var(--color-border-separator)",
        "interactive-focus": "var(--color-border-interactive-focus)",
        "interactive-hover": "var(--color-border-interactive-hover)",
        "interactive-pressed": "var(--color-border-interactive-pressed)",
        "interactive-error": "var(--color-border-interactive-error)",

        // theme: the landing page's ink and its warm off-white (dark mode's text)
        black: "#0A0A0A",

        white: {
          DEFAULT: "#F4F2F0",
          800: "#DCD7D0",
          900: "#F4F2F0",
        },

        // brand tokens that flip with dark mode on their own (styles/brand.css)
        ink: {
          DEFAULT: "var(--sc-ink)",
          2: "var(--sc-ink-2)",
          3: "var(--sc-ink-3)",
          4: "var(--sc-ink-4)",
        },
        line: {
          DEFAULT: "var(--sc-line)",
          2: "var(--sc-line-2)",
        },
        violet: {
          DEFAULT: "var(--sc-violet)",
          soft: "var(--sc-violet-soft)",
          ink: "var(--sc-violet-ink)",
        },
        surface: {
          DEFAULT: "var(--sc-surface)",
          2: "var(--sc-surface-2)",
        },
        page: "var(--sc-page)",
        ground: "var(--sc-bg)",

        "pure-black": "#000",
        "pure-white": "#fff",
      },
      fontFamily: {
        text: "var(--font-family-text)",
        code: "var(--font-family-code)",
        mono: "var(--font-family-code)",
        display: "var(--font-family-display)",
      },
      fontWeight: {
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
        bold: "var(--font-weight-bold)",
      },
      fontSize: {
        base: ["16px", "28px"],
      },
      textColor: {
        "link-code": "var(--sc-violet)",
        code: "#0A0A0A",
        "dark-code": "#DCD7D0",
        marker: "#8B8781",
        "dark-marker": "#8B8781",
      },
      height: {
        navbar: "var(--theme-navbar-height)",
      },
      margin: {
        navbar: "var(--theme-navbar-height)",
      },
      opacity: {
        accent: "var(--theme-accent-opacity)",
      },
      padding: {
        modal: "var(--modal-padding)",
        doc: "var(--doc-padding)",
      },
    },
  },
  plugins: [],
}
